// <auto-generated />
using System;
using EksamensopgaveDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eksamensopgave_S3_1.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20250917084511_opgave_s3_1")]
    partial class opgave_s3_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EksamensopgaveDbContext.Bog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AntalEksemplarer")
                        .HasColumnType("int");

                    b.Property<string>("Forfatter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("UdgivelseDato")
                        .HasColumnType("date");

                    b.Property<string>("Udgiver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BogTabel");
                });

            modelBuilder.Entity("EksamensopgaveDbContext.UdlånBog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AntalBøger")
                        .HasColumnType("int");

                    b.Property<int>("BogId")
                        .HasColumnType("int");

                    b.Property<string>("Låner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("UdlånDato")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BogId");

                    b.ToTable("UdlånBogTabel");
                });

            modelBuilder.Entity("EksamensopgaveDbContext.UdlånBog", b =>
                {
                    b.HasOne("EksamensopgaveDbContext.Bog", "Bog")
                        .WithMany()
                        .HasForeignKey("BogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bog");
                });
#pragma warning restore 612, 618
        }
    }
}
